steps:
  - name: 'gcr.io/cloud-builders/docker@sha256:680b2a8d18a794c165cf97a3f9476784d5d962e945d424cb40b3e086cde0c284'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/rust-http', '.' ]
  - name: 'gcr.io/cloud-builders/docker@sha256:680b2a8d18a794c165cf97a3f9476784d5d962e945d424cb40b3e086cde0c284'
    args: [ 'push', 'gcr.io/$PROJECT_ID/rust-http' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:c2f782e6cafeb04e8780921abdbb83ae948c7e03005671cd0c8bce3296718e60'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rust-http'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rust-http'
      - '--port'
      - '8000'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--cpu'
      - '1'
      - '--memory'
      - '128Mi'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/rust-http'
