steps:
  - name: 'gcr.io/cloud-builders/docker@sha256:3d00b6c1a9b862621c30fc74d4f2abfc62bcbdee631ed3febd31e7edbdf6252c'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/rust-http', '.' ]
  - name: 'gcr.io/cloud-builders/docker@sha256:3d00b6c1a9b862621c30fc74d4f2abfc62bcbdee631ed3febd31e7edbdf6252c'
    args: [ 'push', 'gcr.io/$PROJECT_ID/rust-http' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:c6c6bec5b8b94e4eb2f8ade1f17cf4cb01f07973b7fbb3a4843f0a61592ad5ed'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rust-http'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rust-http'
      - '--port'
      - '8000'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--cpu'
      - '1'
      - '--memory'
      - '128Mi'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/rust-http'
