steps:
  - name: 'gcr.io/cloud-builders/docker@sha256:4a33059c95a600582497fac50780c1c4f68388338fb54002a95b99af85b8f651'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/rust-http', '.' ]
  - name: 'gcr.io/cloud-builders/docker@sha256:4a33059c95a600582497fac50780c1c4f68388338fb54002a95b99af85b8f651'
    args: [ 'push', 'gcr.io/$PROJECT_ID/rust-http' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:96a99902b17be6192e01bd94067d72e9c1c017a042ad970e98eb576070562058'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rust-http'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rust-http'
      - '--port'
      - '8000'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--cpu'
      - '1'
      - '--memory'
      - '128Mi'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/rust-http'
