steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/rust-http', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/rust-http' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rust-http'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rust-http'
      - '--port'
      - '8000'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--cpu'
      - '1'
      - '--memory'
      - '128Mi'
images:
  - 'gcr.io/$PROJECT_ID/rust-http'
